ensures focus in tactic applications for all that depends on bifunctors
exception: DisplayedCartesianMonoidalCategoriesWhiskered.v works with shelving and so there are commands to deactivate that checking for two subsequent lemmas