changing "exact" to "apply" breaks a proof
Perhaps it's a coq 8.4 bug.  Here is the erro message:

    File "./Categories.v", line 478, characters 13-119:
    Error: Impossible to unify
     "compose (pr1 f) (compose (pr1 g) (pr1 h)),, ?370 ==
      compose (compose (pr1 f) (pr1 g)) (pr1 h),, ?388" with
     "compose f (compose g h) == compose (compose f g) h".