adapt the first file of PAdics to the current situation
.package/files: only lemmas.v
Makefile: include PAdics among the packages -> make errors that the other .v files are unlisted in .package/files

lemmas.v:
- a note about editing history
- appropriate import statements
(make complains in the style of
error: *** UniMath/PAdics/lemmas.vo should not require UniMath/Foundations/PartA.vo
Why that?)
- readable reformatting of everything
- use bullet style for proofs (with {} environment for proofs after assert)
- special problems:
  + less than or equal no longer negation of >: use Lemma negnatgthtoleh backwards and natlehneggth forwards
  + hexists cannot be eliminated just through apply: use refine (hinhuniv _ Hyp)
  + some eliminations of negations need first simpl (this can make invisible m <= 0 which has to be reestablished through change)
  + subabmonoids is now subabmonoid in the library

Disclaimer: no effort at all on mathematical issues (elegance, reuse, etc.)